backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages du site"
    files:
      - file: "index.html"
        label: "Page d'Accueil"
        name: "index"
        fields:
          - { label: "Titre principal", name: "hero_title", widget: "string" }
          - { label: "Sous-titre", name: "hero_subtitle", widget: "string" }
          - { label: "Photo de couverture", name: "hero_image", widget: "image" }